### ISSUE TITLE
Get GSC Data: NameError: name 'gscservice' is not defined

### ISSUE THREAD

**Issue by lindsycarter** [jmelm93/query-optmization-checker#1]
I am new to Python but have been following your Moz tutorial and videos, I believe I have the inputs set up correctly but I'm getting this error: **NameError: name 'gscservice' is not defined** in PART 1: Get GSC Data and unable to figure out how to fix this. Can you please point me in the right direction? I'm not able to find other questions about this error online.

`NameError                                 Traceback (most recent call last)`
`<ipython-input-88-16b76ac89b10> in <module>()`
`      6 dimensions=['page','query']`
`      7 `
`----> 8 gsc_df = gscservice.get_site_data(`
`      9     gsc_property,`
`     10     startdate=startdate,`

`NameError: name 'gscservice' is not defined`

**Comment by jmelm93** [comment]
Hey @lindsycarter  - 

A NameError is pretty much saying you're trying to run a function that doesn't exist.

So, the `gscservice` is a function that's defined in the api module (folder) - which is what actually makes the call to the GSC API to aggregate the data. 

1. You'll see `gscservice = GscClient(client)` in `/api/__init__.py`
2. Within the `GscClient(object):`  class in `/api/google_search_console/gsc.py` you'll see `def get_site_data(self, clienturl, startdate, enddate, dimensions, **data):`  

![image](https://user-images.githubusercontent.com/76544513/136640430-e883ca2e-18cd-4be3-99ad-584d6a6dc25d.png)

That `get_site_data` is what this is trying to call that is failing - so it's most likely something wrong with how the api module is setup, but it's hard to know based on the single error code you provided.  

To confirm, does your folder structure look like the below w/ the actual Google Colab file in the `Colab Notebooks` folder?

![image](https://user-images.githubusercontent.com/76544513/136640210-ee4561a2-bae9-4dd4-a7d3-a368b17408b2.png)  

If your folder structure looks accurate, could you upload your code to Github and share the repo with me to troubleshoot?  

If you do upload your files / if you've added your service account into into the `Config.py` file, **please delete that information prior to uploading to Github**, as you don't want that info shared with the public.  

I.e., delete the below information so neither myself or anyone else can see it.   

![image](https://user-images.githubusercontent.com/76544513/136640462-ef237866-df76-4d8c-9559-461c972fbf62.png)

**Comment by lindsycarter** [comment]
Thank you! Total user error. My config wasn't set up right and I just couldn't see it...long week :)
