### ISSUE TITLE
webmaster v3 api is down: UnknownApiNameOrVersion

### ISSUE THREAD

**Issue by spboxer3** [jmelm93/query-optmization-checker#2]
This script used to work well through webmaster v3, but the problem started about 5 days ago, the error log of UnknownApiNameOrVersion appeared when it was running. After checking other scripts that use this API, The same thing seems to have happened.

They gave the solution `searchconsole`, `v1` to replace the API, but after I replaced it in gsc.py, it still doesn't work properly, how can I modify it?

**Comment by jmelm93** [comment]
Ah, sorry for the delay @spboxer3  / my bad I forgot to update the repo when Google update the API earlier this month (*I just pushed a commit with the update right now).  
  
That said, it should only require the below adjustment.  

Is that what you tried to do in the `/api/google_search_console/gsc.py` file and it didn't work?  
  
![image](https://user-images.githubusercontent.com/76544513/141614575-0417266c-749e-4d25-9d15-715c33cdda19.png)

**Comment by spboxer3** [comment]
> Ah, sorry for the delay @spboxer3 / my bad I forgot to update the repo when Google update the API earlier this month (*I just pushed a commit with the update right now).
> 
> That said, it should only require the below adjustment.
> 
> Is that what you tried to do in the `/api/google_search_console/gsc.py` file and it didn't work?
> 
> ![image](https://user-images.githubusercontent.com/76544513/141614575-0417266c-749e-4d25-9d15-715c33cdda19.png)
Yes, here is what I saw. ↓
![image](https://user-images.githubusercontent.com/25055002/141712130-8805892c-fab2-4847-88ed-7fb82a90bc2a.png)
It seems to have entered the 400 error cycle.

**Comment by jmelm93** [comment]
@spboxer3 - the above is saying that it's making the request to the /webmasters/v3/ endpoint still, which is the old endpoint - so that makes sense.  

Can you block out your `CLIENT_ID` / `CLIENT_SECRET` / `GOOGLE_CREDENTIALS` in the `config.py` file and upload your code to Github / share the repo with me so I can take a look / test on my end?  

Below is what you'd need to remove to ensure all your info is safe.   

![image](https://user-images.githubusercontent.com/76544513/141712920-297d9c1b-5f54-48ec-9684-84dc173c3e9d.png)

**Comment by spboxer3** [comment]
Hello @jmelm93 , 
Thanks your help, I added you to my private repo now, please let me know if I'm missing upload file.

**Comment by jmelm93** [comment]
@spboxer3  - your scripts worked fine on my end. 

Few more things might help troubleshoot:  

1. Can you visit https://console.developers.google.com/start/api?id=searchconsole&credential=client_key and ensure this is enabled
2. Can you send me the full `API Error` message you're seeing / showed a snippet of above (**remove / blur out** any personal info from message)
3. Are you using this in Google Colab? Or on another platform? If on another platform, you may need to upgrade your client library with `pip install --upgrade google-api-python-client`
4. Google Colab shouldn't require updating the client library, but just in case, you can also add `!pip install --upgrade google-api-python-client` at the top of the notebook.

*Make sure you restart the runtime after you run `!pip install --upgrade google-api-python-client` - you can do this by going to `Runtime > Factory reset runtime` in top menu.

![image](https://user-images.githubusercontent.com/76544513/141730010-5056cf82-7c5c-4b71-9c8b-42f7efe2573e.png)

**Comment by spboxer3** [comment]
@jmelm93 
1. If you mean the search console API(searchconsole.googleapis.com), I have already enabled it. (I can't enable "https://console.developers.google.com/start/api?id=searchconsole&credential=client_key", it said: Not found or permission denied for service(s))
![image](https://user-images.githubusercontent.com/25055002/141739799-fee26917-8ee4-4e49-8e49-b9369e354454.png)
![image](https://user-images.githubusercontent.com/25055002/141740054-3dd05366-d0ae-4400-858e-3cfb8fd99442.png)

and I try https://console.developers.google.com/start/api?id=searchconsole.googleapis.com&credential=client_key it's worked:
![image](https://user-images.githubusercontent.com/25055002/141739849-ea7655eb-49ec-4180-80df-81bdbe8f2954.png)

2.Here's full API error information. (ignore the red dash line, it's my google extension)
![chrome_XiTYPRcNM4](https://user-images.githubusercontent.com/25055002/141739194-691616bb-e019-45f7-a06d-1adaf5903c2f.jpg)
p.s. I know this domain name looks like testing random domain for script, but I do have permission for this search console.

3. yes, I'm used google colab to execute this notebook.

4. I tried, but it does still not work for me.
![image](https://user-images.githubusercontent.com/25055002/141740429-f8acccdd-007c-4c68-a64c-8bb4ad89112e.png)

Edit: Without any changes, suddenly it worked, thanks for your help.
